# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: "Qilletni Language Docs"
site_description: "Documentation, code examples, and library help for Qilletni"
site_url: "https://qilletni.dev/"
repo_url: "https://github.com/RubbaBoy/Qilletni"

theme:
  name: 'material'
  highlightjs: true
  features:
    - navigation.tracking
#    - navigation.sections
    - navigation.tabs
    - navigation.instant
    - navigation.sections
#    - navigation.expand
    - navigation.prune
    - navigation.path
    - content.code.copy
    - content.code.annotate

extra_javascript:
  - js/playlist_visual.js

extra_css:
  - css/playlist_visual.css
  - css/extra.css

nav:
  - Home:
    - Welcome: index.md
    - Quickstart:
        - Getting Started: quickstart/getting_started.md
        - Spotify Integration: quickstart/spotify_integration.md
        - Last.Fm Integration: quickstart/lastfm_integration.md
    - Project Structure: project_structure.md
    - Language:
        - Introduction: language/introduction.md
        - Syntax:
            - Operators: language/syntax/operators.md
            - Extension Functions: language/syntax/extension_functions.md
        - Types:
            - Built-in types: language/types/built_in_types.md
            - Entities: language/types/entities.md
  #          - Lists*: language/types/lists.md
            - Type system*: language/types/type_system.md
        - Service Providers: language/service_providers.md
        - Documenting Code: language/documenting_code.md
        - Debugging: language/debugging.md
    - Native Binding:
        - Introduction: native_binding/introduction.md
        - Native Functions: native_binding/native_functions.md
        - Native Bind Factories: native_binding/native_bind_factories.md
        - Background Tasks: native_binding/background_tasks.md
        - Usage Examples: native_binding/usage_examples.md
    - Misc:
      - Package Configs: package_configs.md
      - Hosting Docs: misc/hosting_docs.md
  - Packages:
      - Introduction: packages/introduction.md
      - Standard Library: packages/std.md
      - Spotify: packages/spotify.md
      - LastFm: packages/lastfm.md
      - JSON: packages/json.md
      - Metadata: packages/metadata.md
      - HTTP: packages/http.md
      - Postgres: packages/postgres.md
  - Examples:
    - General: examples.md

markdown_extensions:
  - attr_list
  - toc
#      permalink: true
  - tables
  - admonition
  - codehilite:
      use_pygments: true
      guess_lang: false
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
